version: '2'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb

  rest:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app:Z
    links:
      - mongodb